# ID -> (reason pointers, example pointers); joined with new lines in the sheet
def B(*x): return '\n'.join('• '+i for i in x)
SAME=lambda k: (B(f'Same reason as {k}'), B(f'See example in {k}'))
DET={
'S03':(B('Status: MATCHES (diff only 0.2%)',
         'Why small gap: admin corrected weekly_os in MV after the Sheet was made',
         'Rows different: 9 of 79,600 partner-weeks',
         'Fix needed: None'),
       B('Partner: ETM04252','Week: 14-Sep','Sheet OS: -172,288','MV OS: -160,288','Diff: 12,000 (MV corrected later)')),
'S04':(B('Status: MATCHES (diff 0.1%)',
         'Why small gap: 5 rows where the Sheet had a wrong collection value',
         'Fix needed: None'),
       B('Partner: ETM88689','Week: 31-Aug','Sheet collected: 755,025 (wrong entry in Sheet)','MV collected: 1,025')),
'S05':(B('Status: FIXED in query - now matches',
         'Old problem: query took Razorpay = Total - other modes, so it could go NEGATIVE',
         'Sheet rule: fill modes in order Razorpay -> Other -> Phonepe -> Adjustment -> DP-to-Rent',
         'Sheet rule: each mode is counted only up to the OS still unpaid',
         'Before fix: 19.7% rows different',
         'After fix: 0 of 79,600 rows different'),
       B('Partner: ETN81418','Week: 17-Aug','Razorpay paid 3,744 = full OS',
         'Sheet: Razorpay 3,744 | Adjustment 0','Old query: Razorpay -3,256 | Adjustment 7,000','Now: Razorpay 3,744 | Adjustment 0 (same as Sheet)')),
'S08':(B('Status: FIXED in query - now matches',
         'Old problem: query counted the FULL positive adjustment',
         'Sheet rule: adjustment counted only if OS is still unpaid after Razorpay/Other/Phonepe',
         'Before fix: 15.9% rows different',
         'After fix: 2 of 79,600 rows different'),
       B('Partner: ETN80714','Week: 21-Sep','Adjustment posted: 7,000','OS already fully paid by Razorpay',
         'Sheet: 0','Old query: 7,000','Now: 0')),
'S09':(B('Status: FIXED in query - now matches',
         'Old problem: query counted the FULL deposit-to-OS amount',
         'Sheet rule: deposit-to-OS counted only up to the OS left; extra = advance',
         'Before fix: 2.6% rows different',
         'After fix: 1 of 79,600 rows different'),
       B('Partner: ETN58831','Week: 31-Aug','OS left: 67','Deposit used: 63,763',
         'Sheet DP-to-Rent: 67 (extra 63,696 = advance)','Old query: 63,763','Now: 67')),
'S11':(B('Status: FIXED in query','Same waterfall rule as S05 / S08 / S09'),B('See examples in S05, S08, S09')),
'S14':(B('Status: MV DATA WRONG - fix in MV',
         'Why: MV helper column previous_week_collection is 0 for EVERY partner',
         'So: MV flag becomes 1 when only ONE previous week was unpaid',
         'Sheet rule: count partner only if BOTH previous 2 weeks unpaid',
         'Rows different: 14.3% of partner-weeks',
         'Impact (Delhi Own Now, 7 weeks): MV 450 vs Sheet 238',
         'Fix in MV (1): fill previous_week_collection = payments 2 weeks back',
         'Fix in MV (2): flag = 1 only when both weeks unpaid'),
       B('Partner: ETN65068',
         'Week 17-Aug: unpaid weeks = 1 -> Sheet NOT counted | MV flag 1 (counted - wrong)',
         'Week 31-Aug: unpaid weeks = 2 -> Sheet counted | MV flag 0 (missed - wrong)',
         'Partner: ETB059833, week 14-Sep: paid 1,800 in 07-13 Sep but MV still says not paid')),
'S15':(B('Status: FIXED in query - now matches',
         'Old problem: MV till-Wed amount is not capped',
         'Sheet rule: till-Wed collection counted only up to partner OS',
         'Query now: till_wed_100pct = smaller of (till-Wed paid, OS)',
         'After fix: 1 of 79,600 rows different'),
       B('Partner OS: 5,000','Paid by Wednesday: 8,000','Sheet: 5,000','MV column: 8,000','Query now: 5,000')),
'S17':(B('Status: MV DATA WRONG - fix in MV',
         'Metric uses "active full week" = total_allocated_days >= 7',
         'Problem 1: car-swap day counted twice (8 days in a 7-day week)',
         'Problem 2: some rows add driven week + hisaab week (14 days)',
         'Also: Sheet used "Uber active 7 days", MV uses "allocated 7 days"',
         'Rows wrong in MV: 3.5%',
         'Impact (Delhi Own Now): MV 967.2K / 48 partners vs Sheet 34.2K / 4',
         'Fix in MV: count DISTINCT allocated dates inside hisaab week only',
         'Decide: active = allocated 7 days OR Uber-active 7 days'),
       B('Partner: ETB05220, week 14-Sep: car swapped mid-week -> 2 allocation rows -> MV 8 days (real 7)',
         'Partner: ETB02245, week 14-Sep: MV 14 days = 7 driven + 7 hisaab (real 7)')),
'S18':(B('Status: NEW in query (Sheet tab was empty)',
         'Old Sheet OS_Surpass tab showed 0 for everything',
         'Query: OS above deposit, only Active partners',
         'Fix needed: None - confirm weekly snapshot is OK for "Live"'),
       B('Active partner OS: -45,000','Week-end deposit: 40,000','Surpass amount: 5,000','Bucket: 2K-5K','Sheet showed: 0')),
'S19':SAME('S18'),
'S21':(B('Status: MV CORRECT (MV is the corrected logic)',
         'Why gap: admin DAG fix re-dated / removed some bad debt after Sheet was built',
         'Rows different: 0.6% (mostly weeks 21-Sep and 28-Sep)',
         'Fix needed: None'),
       B('Partner: ETN84045','Week: 28-Sep','Sheet bad debt: -8,684','MV bad debt: none in any week (removed by DAG fix)',
         'Partner: ETN090225, 28-Sep: Sheet -5,377 | MV none')),
'S22':SAME('S21'),
'S23':(B('Status: MV DATA WRONG - fix in MV',
         'Why 1: MV adds the partner\'s OWN deposit used to clear OS (not cash)',
         'Why 2: MV keeps a RUNNING TOTAL, so old amounts repeat every week',
         'Why 3: MV fills it even when partner never rejoined',
         'Rows wrong: 23.9%',
         'Impact (all India, 4 weeks): MV 65.8M vs Sheet 1.37M',
         'Fix in MV: only real cash payments (razorpay / phonepe / other)',
         'Fix in MV: only between leave date and next join date, that week only',
         'Fix in MV: 0 if partner did not rejoin'),
       B('Partner: ETB02477','Week: 14-Sep','Left (jama): 07-Sep, never rejoined',
         'MV shows: 6,000','= 4,765 deposit used on 08-Sep (already shown in 07-Sep week)','+ 1,235 deposit used on 15-Sep',
         'Correct value: 0')),
'S24':(B('Status: DEFINITION TO CONFIRM',
         'Query: all collections of Inactive partners after their first bad-debt week',
         'Query includes deposit-to-OS amounts',
         'Sheet column was almost always 0',
         'Rows different: 1.6%',
         'Suggestion: count only cash payments, exclude deposit-to-OS'),
       B('Partner: ETN01260','Week: 31-Aug','Partner became Inactive','Deposit used: 26,848',
         'Query funnel: 26,848','Sheet: 0','Week 07-Sep: same pattern (6,145)')),
'S25':(B('Follows S21 / S23 / S24'),B('See examples in S21, S23, S24')),
'S26':(B('Status: MV CORRECT (Sheet column was mislabeled)',
         'Sheet "week start deposit" actually held the latest (week-END) deposit',
         'MV week_start_deposit = deposit BEFORE the week (validated 100%)',
         'Rows different: 19.6% (partners who topped up deposit during week)',
         'Fix needed: None'),
       B('Partner: ETN69666','Week: 31-Aug','Sheet week-start deposit: 167,575',
         'MV week-start deposit: 63,000','MV week-end deposit: 167,575','=> deposit added during the week')),
'S27':(B('Status: SAME RULE as Sheet',
         'Rule: Yes if (paid - OS) gap is bigger than deposit',
         'Why gap: deposit value comes from different source (Sheet upload vs MV)',
         'Rows different: 0.5%'),
       B('Partner: ETN78958','Week: 07-Sep','OS: -54,313 | Paid: 40,000 | Gap: 14,313',
         'Sheet deposit: 40,000 -> No','MV week-end deposit: 0 -> Yes')),
'S28':(B('Status: NEW in query (Sheet tab missing)',
         'Old Sheet car_recovery_data tab did not exist (#REF -> 0)',
         'Now taken from recovery_cars table',
         'Fix needed: None'),
       B('Delhi Own Now, week 14-Sep','recovery_cars: 138 recoveries created','Sheet: 0 (tab missing)')),
'S29':SAME('S28'),'S30':(B('Same reason as S28','Confirm: "cancelled" status = organic return'),B('See example in S28')),
'S31':SAME('S28'),'S32':SAME('S28'),'S33':SAME('S28'),'S34':SAME('S28'),'S35':SAME('S28'),
'S36':(B('Status: SAME SCORE LOGIC as Sheet - inputs differ',
         'Score = count of 6 signals: unpaid prev weeks, recovery Yes, Defaulter, ND > 2, GPS off, 0 connects',
         'Why 1: Sheet ND / GPS / connects came from uploads pasted by ROW POSITION (misaligned)',
         'Why 2: Sheet counted 03-Aug week for unpaid check (week not in MV)',
         'Rows in different bucket: 29.4%',
         '05-Oct No risk: query 5,170 vs Sheet 5,672',
         '05-Oct Moderate: query 584 vs Sheet 509',
         'Fix needed: None in MV - query uses partner-matched PG data'),
       B('Partner: ETN77730','Week: 17-Aug',
         'Sheet: High risk = 5 signals (unpaid 1, Defaulter, ND 7, GPS 1, connects 0)',
         'Query: Moderate = 4 signals',
         'Only difference: unpaid prev 2 weeks = 0 (03-Aug week not in MV)',
         'Partner: ETN063945, 05-Oct: Sheet Moderate = Query Moderate')),
'S37':(B('Status: DIFFERENT RULE - decision needed',
         'MV: habit of PREVIOUS week (driver_repayment_habit, agreed rule #14)',
         'Sheet: habit of CURRENT week by formula',
         'Sheet formula: paid till Wed >= OS -> Very Good; paid >= OS -> Good; >= 75% -> Average; else Defaulter',
         'Rows different: 55.2%',
         'Query also gives payment_habit_week (Sheet formula) -> matches Sheet 99.9%',
         'Decide: keep MV rule OR use Raw_Data BA payment_habit_week in Summary'),
       B('Partner: ETN086508','Week: 17-Aug','Paid 75-99% of OS this week',
         'Sheet: Average (this week)','MV: Defaulter (last week)')),
'S38':(B('Same reason as S26 (Sheet deposit = week-end value)'),
       B('Partner: ETN69666, 31-Aug','Sheet: 167,575','MV: 63,000','Other partners move between buckets for same reason')),
'S39':(B('Status: DEFINITION TO CONFIRM',
         'Query: deposit BALANCE on allocation date (mostly 20K+)',
         'Sheet: deposit PAID at allocation (mostly 2K-20K)',
         'If "paid at allocation" wanted: use initial-deposit / top-up on allocation date'),
       B('Partner allocated 01-Sep','Total deposit held: 30,000','Paid at that allocation: 5,000',
         'Query: 30,000 -> bucket 20K+','Sheet: 5,000 -> bucket 5K-10K')),
'W02':(B('Status: MATCHES (diff 1%)','Why gap: admin weekly_os fix after Sheet snapshot'),B('See example in S03')),
'W05':(B('Status: FIXED in query','Same waterfall rule as S09'),B('See example in S09')),
'W06':(B('Status: FIXED in query','Same waterfall rule as S09'),B('See example in S09')),
'W08':SAME('S21'),'W09':SAME('S24'),'W10':SAME('S23'),
'W11':(B('Status: MV CORRECT - WBR logic fixed',
         'MV carry-forward has owed amounts (negative) AND credits (positive)',
         'WBR needs only OWED amounts',
         'Old sum netted credits: 26.0M vs Sheet 57.8M',
         'Query now: carry_forward_os_neg = negative part only -> 59.9M',
         'Remaining 0.3% rows: first week of Sheet had no previous-week row'),
       B('Partner: ETN41666','Week: 17-Aug','MV carry-forward: -6,000',
         'Sheet: 0 (Sheet had no 10-Aug row for this partner)','From 24-Aug: Sheet = MV (-4,995, -2,498, -4,899)')),
'W12':SAME('S17'),'W13':SAME('S36'),
'W14':(B('Status: FIXED in query (row level)',
         'Sheet rule: advance = everything paid above OS, INCLUDING deposit-to-OS',
         'Old query subtracted deposit-to-OS',
         'Now: advance = paid - OS (if positive) -> 99.99% rows match',
         'Remaining WBR gap: old WBR read a separate upload tab (advance_payment_data)',
         'Partners: query 15,314 vs old WBR 11,199',
         'Decide: which advance definition WBR should use'),
       B('Partner: ETN58831','Week: 31-Aug','OS left: 67','Deposit used: 63,763',
         'Sheet advance: 63,696','Old query: 0','Now: 63,696')),
}
