SL={
'S01':'City_Targets: ABS(Target Amt) / ABS(Total OS) for week + city + product',
'S02':'SUM(till_sun_100pct = MIN(total_recovery, |OS|)) / ABS(SUM(negative_os)); OS + recovery from uploaded sheets (collections_data, IMPORTRANGE)',
'S03':'SUM(negative_os) from uploaded weekly OS sheet',
'S04':'Razorpay + Other + Phonepe + Adjustments + DP-to-Rent (100% columns P..T)',
'S05':'P = MIN(razorpay_recovery, |OS|); razorpay from collections_data tab',
'S06':'Q = MAX(0, MIN(other_recovery, |OS| - razorpay))',
'S07':'R = MAX(0, MIN(phonepe, |OS| - razorpay - other))',
'S08':'S = MAX(0, MIN(adjustments, |OS| - razorpay - other - phonepe))',
'S09':'T = MAX(0, MIN(dp_to_os, |OS| - razorpay - other - phonepe - adjustments))',
'S10':'SUM(total_recovery incl. advance, collections_data) / ABS(SUM(OS))',
'S11':'Each mode (P..T) / Total Actual Collections',
'S12':'COUNTUNIQUE(partner) where negative_os < 0',
'S13':'COUNT partners where OS < 0 AND total_recovery = 0',
'S14':'COUNT where not_paid_last_2_weeks > 1; col AA = no. of own rows in previous 2 weeks with total_recovery = 0',
'S15':'SUM(till_wed_100pct = MIN(till-Wed collection, |OS|)) / ABS(SUM(OS))',
'S16':'(Razorpay + Other + Adjustments) / ABS(OS)',
'S17':'SUM / COUNT of dp_to_os_100pct where entire_week_active > 0 (upload) and dp_to_os > 0; % = / ABS(OS)',
'S18':'OS_Surpass tab (separate upload) - was empty (0)','S19':'OS_Surpass tab (separate upload) - was empty (0)',
'S20':'City_Targets: ABS(Target Bad Debt) / ABS(Total OS)',
'S21':'SUM(bad_debt) (uploaded col AW); % = / SUM(OS)',
'S22':'COUNT partners with bad_debt < 0; % = / pilots in negative; per partner = amount / count',
'S23':'NonFunnel_BadDebt_Collected tab (upload) - formula was #REF (blank)',
'S24':'SUM(bad_debt_rec_100pct) (uploaded col AY); % = / ABS(bad debt)',
'S25':'Bad debt + collected; % = / OS',
'S26':'AVERAGE deposit from sd_bucket tab (IMPORTRANGE deposit sheet = latest deposit)',
'S27':'Col AH: IF(net_os >= 0, No, IF(|net_os| > week_end_deposit, Yes, No)); net_os = till_sun_100pct - |OS|',
'S28':'car_recovery_data tab - tab missing (#REF -> 0)','S29':'car_recovery_data tab - missing (0)','S30':'car_recovery_data tab - missing (0)',
'S31':'car_recovery_data tab - missing (0)','S32':'car_recovery_data tab - missing (0)','S33':'car_recovery_data tab - missing (blank)',
'S34':'car_recovery_data tab - missing (blank)','S35':'car_recovery_data tab - missing (blank)',
'S36':'Col AL: score of 6 signals (AA unpaid, AH recovery, AF Defaulter, AG ND > 2, AI GPS = 1, AK connects <= 0) -> bucket; ND / GPS / connects from IMPORTRANGE uploads',
'S37':'Col AF (current week): OS = 0 Excellent; till-Wed >= OS Very Good; paid >= OS Good; >= 75% Average; else Defaulter',
'S38':'sd_bucket tab (IMPORTRANGE) - count partners per deposit bucket',
'S39':'sd_bucket_V2 tab (IMPORTRANGE) - deposit paid at allocation per bucket',
'W01':'City_Targets: ABS(Target Amt) / ABS(Total OS)',
'W02':'ABS(SUM(negative_os where <= 0)) by week / city / product',
'W03':'SUM(till_sun_100pct) by week / city / product',
'W04':'SUM(till_sun_100pct) / ABS(SUM(negative_os))',
'W05':'SUM(till_sun_100pct) - SUM(dp_to_os_100pct)',
'W06':'(SUM(till_sun_100pct) - SUM(dp_to_os_100pct)) / ABS(SUM(OS))',
'W07':'Product block / all-product value; Not collected = |collection share - OS share|',
'W08':'COUNTUNIQUE bad_debt < 0; ABS(SUM(bad_debt)); SUM(bad_debt) / SUM(OS)',
'W09':'SUM(bad_debt_rec_100pct) where bad_debt < 0 (same row)',
'W10':'NonFunnel_BadDebt_Collected tab (upload) by week / city / product',
'W11':'SUM(prev_carry_forward); prev = previous week row of carry_forward_os = MIN(OS + recovery, 0)',
'W12':'SUM(dp_to_os_100pct where entire_week_active = 1) / ABS(OS); COUNTUNIQUE partners',
'W13':'COUNTUNIQUE asset_risk not in (No, Minimal, Low risk); % = / partners with OS <= 0',
'W14':'advance_payment_data tab (upload): advance_amount by week / city / product',
'W15':'COUNTUNIQUE partner where negative_os <= 0',
'W16':'COUNTUNIQUE partner by negative_os bucket; % = / partners with OS <= 0',
}
ML={'W01':'City_Targets (same table): ABS(Target Amt) / ABS(Total OS)','W02':'ABS(SUM(total_os where total_os <= 0))','W03':'SUM(total_collected_100_pct)',
'W04':'SUM(total_collected_100_pct) / ABS(SUM(total_os))',
'W08':'COUNTUNIQUE partners with bad_debt_amount < 0; ABS(SUM(bad_debt_amount)); SUM(bad_debt_amount) / SUM(total_os)',
'W09':'SUM(bad_debt_collected_funnel) = total_collected_100_pct of Inactive partners after their first bad-debt week',
'W10':'SUM(bad_debt_collected) from MV for the week',
'W13':'COUNTUNIQUE partners where asset_risk not in (No risk, Minimal Risk, Low Risk)'}
JO={'W09':'bd CTE: MIN(hissab_week) where bad_debt_amount < 0, LEFT JOIN on partner_etm','W13':'collections_bad_debt_mv history (unpaid window) + mv_collections_calling_masterlist on partner_et_id + week (latest snapshot)'}
SRC={'W09':'collections_bad_debt_mv (history) + total_collected_100_pct','W13':'Derived: MV + mv_collections_calling_masterlist'}
