exec(open('write_tab.py').read().split('MAN,REM=pickle.load')[0])
V2='MV_Raw_Data_Manual_Check_v2'
o=json.load(open(f'pct_{TAB}.json'))['pct']
hdr=call('GET',f"{API}/{SID}/values/'{V2}'!A5:ZZ5")['values'][0]
r2=call('GET',f"{API}/{SID}/values/'{V2}'!A2:ZZ2")['values'][0]
v={h[:-9]:r2[j] for j,h in enumerate(hdr) if h.endswith(' Matched?') and j<len(r2)}
def imp(f): return f' [Original tab {o.get(f)} → this tab {v.get(f)}]'
T={
'weekly_os':('CONFIRMED: weekly_os is a direct column in fleet_leasing_weeklydata – no calculation. Gap = partner has 2+ rows in driven week; MV keeps only rows with rent/active days and drops "adjustment-only" rows (rent 0, days 0, e.g. -1000 fine on old car). Example: ETB059697 rows -6,785 + -500 → MV -6,785, sum -7,285.','DAG: sum weekly_os of ALL driven-week rows (or confirm fines go to carry-forward). Employee-level rows are in tab weekly_os_detail.','1) Open tab weekly_os_detail (all rows of the 471 partners). 2) Check the "Adjustment-only" rows. 3) Decide include/exclude → DAG change. Expected 95.6% → 100%.'),
'prev_carryforward_os':('NEW RULE: last week net OS = last week MV total_os + last week total_collected_amount_in_week. Gaps: (A) 1,213 overpaid last week (credit) but MV carries 0, e.g. ETB04273 net +175 → MV 0; (B) 582 gap = fixed fine (-1000/-175/-500), e.g. ETB060010 net 0 → MV -1,001; (C) 347 no row last week.'+imp('prev_carryforward_os'),'DAG/business: decide if credit (overpaid) carries forward or goes to deposit; add fines explicitly; for new partners use 0.','1) Filter Remark "overpaid" → confirm credit rule. 2) Filter Remark "fixed fine" → list fine source (fleet_leasing_weeklydata adjustment rows / negative_adjustment). 3) Update DAG. Expected 72% → 95%+.'),
'last_jama_date':('SSOT check: 2,648 match. 7,927 car still allocated at hisaab end → MV shows placeholder 21-Oct (refresh date + 14). 109 car returned (e.g. ETB060105 returned 01-Oct) but MV still 21-Oct. 127 SSOT jama changed after MV refresh.','DAG: last_jama_date = max(jama_date) from ssot_alloc_dealloc_base where jama_date <= hisaab week end; blank if car not returned.','1) Remove placeholder date logic. 2) Re-run MV. Expected 23.5% → 98%+.'),
'week_start_deposit':('NEW RULE: sum of mv_deposits_raw with date <= hisaab week start (28-Sep). FOUND: MV ignores deposit types SD_TO_OWNNOW / OWNNOW_TO_OWNNOW (deposit moved to Own Now). Example: ETB00839 -30,000 SD_TO_OWNNOW on 15-Apr → raw 0, MV 30,000. Excluding those types MV matches 100%.'+imp('week_start_deposit'),'Business: should deposit moved to Own Now reduce deposit? If yes → DAG include these types; also use <= 28-Sep (52 rows have entry on 28-Sep).','1) Confirm Own Now rule. 2) DAG: include SD_TO_OWNNOW / OWNNOW_TO_OWNNOW and date <= hisaab week start. Expected 91.9% → 100%.'),
'week_end_deposit':('NEW RULE: sum of mv_deposits_raw with date <= hisaab week end (04-Oct). Same finding: MV ignores SD_TO_OWNNOW / OWNNOW_TO_OWNNOW (830 partners). Excluding them MV = 100%.'+imp('week_end_deposit'),'Same decision as week_start_deposit.','Same as week_start_deposit. Expected 92.3% → 100%.'),
'last_week_payment_habit':('Logic is fine. Only 3 cases: brand-new partners (ETK00260, ETK04617, ETN63917) – first habit entry is for 28-Sep week itself, so nothing before hisaab week; MV puts default "Excellent".','Business: is "Excellent" the default for new partners? If yes → mark as matched.','No DAG change needed if default is agreed.'),
'tenure_days':('NEW RULE: 7-day delta accepted. MV counts till hisaab Sunday (+7). Partners who left during hisaab week show +2 to +5 (MV counts till leave date). With delta 0–7 accepted → 100% match.'+imp('tenure_days'),'No action (or DAG: till driven week end if exact match is needed).','—'),
'last_week_nd_count':('CHECKED with allocation + dailytrip (day level): ND = allocated days with no trip. MV matches only 79%. Example: ETB01547 allocated 7 days, 0 trips → ND 7, MV 0. Tried: partial days, D2O leave, Ola trips, leasing active_days – none explain MV. So MV ND comes from another source.','Ask DAG owner for ND source. If allocation + dailytrip is the agreed rule → change DAG.','1) Get ND logic from admin. 2) Agree rule. 3) Re-run. Expected 79% → 100% with agreed rule.'),
'current_week_nd_count':('Same check for hisaab week: MV matches 82%. Example: ETB01547 allocated 5 days, 0 trips → ND 5, MV 1.','Same as last_week_nd_count.','Same as last_week_nd_count.'),
'hissab_week_active_days':('CHECKED: MV is NOT trip days. MV = allocated days across driven + hisaab week (14 = both weeks full), 97.8% of rows follow this. Days with trips in hisaab week (dailytrip) match only 0.1%. Example: ETB00514 MV 14, car ran 7 days.','DAG: count distinct dailytrip dates with trips > 0 in hisaab week (or rename field).','1) Change DAG. 2) Re-run. Expected 0.1% → 100%.'),
'active_inactive_flag':('NEW RULE checked for each week: allocated on min(hisaab week end, today). 21-Sep: 89.8% (1,104 returned car mid-week, MV Active). 28-Sep: 89.6% (1,116). 05-Oct (current week): 17.9% – MV shows 8,998 partners Inactive although allocated today (bug for running week).','DAG: flag = allocated on min(hisaab_week_end, today). Fix current-week logic.','1) Change DAG rule. 2) Re-run all weeks. Expected 89% → 99.9%.'),
'next_join_date':('NEW RULE: only for partners who attrited in driven/hisaab week and did not rejoin till hisaab week end (value = next join date, blank if not rejoined). 6,595 never-left partners have placeholder 21-Oct; 365 not attrited have a date; 173 rejoined after MV refresh (MV blank). Example: ETB01090 left 03-Oct, rejoined 08-Oct → MV blank.'+imp('next_join_date'),'DAG: blank for partners not attrited; for attrited take first allocation after jama; refresh after week closes.','1) Remove placeholder. 2) Re-run. Expected 34% → 95%+.'),
'bad_debt_collected':('CHECKED: MV = whole hisaab-week collection for 6,224 of 6,405 rows. 3,867 never left (should be 0), e.g. ETB00839 MV 9,425 → 0. For partners who left, collections between leave date and rejoin match 1,773 of 2,538; e.g. ETB01090 left 03-Oct, MV 4,282 = whole week.'+imp('bad_debt_collected'),'DAG: 0 if partner never left; else sum collections from jama date to next join date (or hisaab week end).','1) Change DAG. 2) Re-run. Expected 57% → 95%+.'),
'previous_week_collection':('Used only as helper: partners_not_paid_2_weeks = 1 exactly when last_week_collection = 0 AND previous_week_collection = 0 (100% of rows). Not used anywhere else in data. DAG script not accessible to confirm.','If partners_not_paid_2_weeks is computed inside DAG, this column can be dropped from MV.','Confirm with admin; no fix needed.'),
'active_fleet_cash_blocked':('NEW RULE checked with cash-block data at min(today, hisaab week end)=04-Oct: driver_cashblock_details last entry BLOCK → 50% match; driver_cashblock_details_logs (WEEKLY/LIVE) → 46–48%. MV flag (7,304 = 1) matches 92% with "partner has any cash-block record", so MV is NOT block status.'+imp('active_fleet_cash_blocked'),'DAG: flag = 1 if latest cash-block entry on/before min(today, hisaab week end) is BLOCK.','1) Confirm which table = cashblock API data. 2) Change DAG. Expected 50% → 100%.'),
}
data=[]
for f,(i,a,s) in T.items():
    c=col(hdr.index(f+' (MV)'))
    data.append({'range':f"'{V2}'!{c}1:{c}3",'values':[[i],[a],[s]]})
data.append({'range':f"'{V2}'!A4",'values':[['Copy with NEW rules (13 points). Original tab unchanged. [Original % → this tab %] shown in Issue.']]})
call('POST',f'{API}/{SID}/values:batchUpdate',json={'valueInputOption':'USER_ENTERED','data':data})
meta=call('GET',f'{API}/{SID}',params={'fields':'sheets.properties'})
tid=[s['properties']['sheetId'] for s in meta['sheets'] if s['properties']['title']==V2][0]
call('POST',f'{API}/{SID}:batchUpdate',json={'requests':[{'updateDimensionProperties':{'range':{'sheetId':tid,'dimension':'ROWS','startIndex':0,'endIndex':1},'properties':{'pixelSize':150},'fields':'pixelSize'}},
 {'repeatCell':{'range':{'sheetId':tid,'startRowIndex':3,'endRowIndex':4,'startColumnIndex':0,'endColumnIndex':1},'cell':{'userEnteredFormat':{'textFormat':{'bold':True,'foregroundColor':{'red':0.7,'green':0,'blue':0}},'wrapStrategy':'OVERFLOW_CELL'}},'fields':'userEnteredFormat(textFormat,wrapStrategy)'}}]})
print('ok')
